# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cbaff6280ebea4d9f130dfe4165be4583a804510bc3e29f67481948f33352d5a55a4260556e4f19f3f8d5bcddb0a268c3cbc39634b9e3c2b3a93d2077148bd

test:
  secret_key_base: a442539f016bf5884ab1ee09b9a8dbd485cb752fedb4b1a2c9af9e67fa2a6a524d693141c3aba893e3ad1bd903b3e92e73fa38f4b834631193e376630d74c516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
